<?php
/* GIS training — the master chapter list (from "GIS-ArcGIS-Training Chapters List.md").
   Drives the course index, the chapter topbars and the prev/next links.
   status: 'ready' = tutorial built (dir + modules), 'drafted' = chapter document written, 'planned' = on the curriculum only. */
return [
  [
    'id' => 'phase-1', 'n' => 'Phase 1', 'title' => 'Understand GIS and the ArcGIS ecosystem',
    'intro' => 'Introduce the ecosystem early so developers understand where the foundational concepts will be used. Small practical exercises throughout — do not wait until Chapter 12 to open a GIS application.',
    'checkpoint' => 'Given unfamiliar data, the trainee can explain its structure and CRS, identify quality problems, perform a basic spatial analysis, and justify the result.',
    'chapters' => [
      ['n' => 1, 'title' => 'GIS fundamentals and spatial thinking', 'desc' => 'What GIS solves; location, distribution, proximity, and spatial relationships. Turning a business question into a geographic question.', 'status' => 'ready', 'dir' => 'Chapter_01', 'modules' => [
        ['id' => '1.1', 'file' => 'm1-decision', 'title' => 'Start with a decision'],
        ['id' => '1.2', 'file' => 'm2-gis', 'title' => 'What a GIS includes'],
        ['id' => '1.3', 'file' => 'm3-spatial', 'title' => 'Spatial thinking'],
        ['id' => '1.4', 'file' => 'm4-data', 'title' => 'Data and its meaning'],
        ['id' => '1.5', 'file' => 'm5-layers', 'title' => 'Layers and map interaction'],
        ['id' => '1.6', 'file' => 'm6-limits', 'title' => 'Limits of a conclusion'],
        ['id' => '1.7', 'file' => 'm7-lab', 'title' => 'Lab: problem brief'],
        ['id' => '1.8', 'file' => 'm8-check', 'title' => 'Independent check'],
        ['id' => '1.9', 'file' => 'm9-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 2, 'title' => 'Understanding the ArcGIS ecosystem', 'desc' => 'The roles of ArcGIS Pro, ArcGIS Online, ArcGIS Enterprise, configurable applications, APIs, and SDKs. A simple demonstration of data becoming a map and an application.', 'status' => 'ready', 'dir' => 'Chapter_02', 'modules' => [
        ['id' => '2.1', 'file' => 'm1-responsibilities', 'title' => 'Five responsibilities'],
        ['id' => '2.2', 'file' => 'm2-pro', 'title' => 'ArcGIS Pro'],
        ['id' => '2.3', 'file' => 'm3-online', 'title' => 'ArcGIS Online'],
        ['id' => '2.4', 'file' => 'm4-enterprise', 'title' => 'ArcGIS Enterprise'],
        ['id' => '2.5', 'file' => 'm5-apps', 'title' => 'Apps, APIs, SDKs'],
        ['id' => '2.6', 'file' => 'm6-platforms', 'title' => 'Other platforms'],
        ['id' => '2.7', 'file' => 'm7-lab', 'title' => 'Lab: trace a solution'],
        ['id' => '2.8', 'file' => 'm8-check', 'title' => 'Independent check'],
        ['id' => '2.9', 'file' => 'm9-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 3, 'title' => 'Geographic data: features, geometry, attributes, and layers', 'desc' => 'How real-world objects become GIS records. Points, lines, polygons, multipart geometry, attributes, datasets, and layers.', 'status' => 'ready', 'dir' => 'Chapter_03', 'modules' => [
        ['id' => '3.1', 'file' => 'm1-representation', 'title' => 'Real thing vs its shape'],
        ['id' => '3.2', 'file' => 'm2-geometry', 'title' => 'Point, line, polygon'],
        ['id' => '3.3', 'file' => 'm3-structure', 'title' => 'Parts, holes, formats'],
        ['id' => '3.4', 'file' => 'm4-attributes', 'title' => 'Attributes'],
        ['id' => '3.5', 'file' => 'm5-layers', 'title' => 'Dataset, layer, map'],
        ['id' => '3.6', 'file' => 'm6-inspect', 'title' => 'Extent, count, edits'],
        ['id' => '3.7', 'file' => 'm7-lab', 'title' => 'Lab: inspect a town'],
        ['id' => '3.8', 'file' => 'm8-check', 'title' => 'Independent check'],
        ['id' => '3.9', 'file' => 'm9-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 4, 'title' => 'Raster data and geographic surfaces', 'desc' => 'Pixels, resolution, bands, NoData, imagery, and elevation. Choosing between vector and raster representations.', 'status' => 'ready', 'dir' => 'Chapter_04', 'modules' => [
        ['id' => '4.1', 'file' => 'm1-grid', 'title' => 'The raster model'],
        ['id' => '4.2', 'file' => 'm2-values', 'title' => 'Values, colours, bands'],
        ['id' => '4.3', 'file' => 'm3-resolution', 'title' => 'Resolution & extent'],
        ['id' => '4.4', 'file' => 'm4-nodata', 'title' => 'NoData'],
        ['id' => '4.5', 'file' => 'm5-resampling', 'title' => 'Resampling'],
        ['id' => '4.6', 'file' => 'm6-surfaces', 'title' => 'Elevation & 3D'],
        ['id' => '4.7', 'file' => 'm7-lab', 'title' => 'Lab: inspect two rasters'],
        ['id' => '4.8', 'file' => 'm8-check', 'title' => 'Independent check'],
        ['id' => '4.9', 'file' => 'm9-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 5, 'title' => 'Coordinates and coordinate reference systems', 'desc' => 'Latitude/longitude, X/Y, units, coordinate order, datums, geographic/projected systems, and EPSG identifiers.', 'status' => 'ready', 'dir' => 'Chapter_05', 'modules' => [
        ['id' => '5.1', 'file' => 'm1-two-numbers', 'title' => 'Two numbers are not a place'],
        ['id' => '5.2', 'file' => 'm2-latlon', 'title' => 'Latitude and longitude'],
        ['id' => '5.3', 'file' => 'm3-earth-model', 'title' => 'Shape, ellipsoid, datum'],
        ['id' => '5.4', 'file' => 'm4-geo-vs-projected', 'title' => 'Geographic vs projected'],
        ['id' => '5.5', 'file' => 'm5-order', 'title' => 'Coordinate order'],
        ['id' => '5.6', 'file' => 'm6-height', 'title' => 'Height and Z'],
        ['id' => '5.7', 'file' => 'm7-inspect', 'title' => 'Data CRS vs map CRS'],
        ['id' => '5.8', 'file' => 'm8-lab', 'title' => 'Lab: coordinate detective'],
        ['id' => '5.9', 'file' => 'm9-check', 'title' => 'Independent check'],
        ['id' => '5.10', 'file' => 'm10-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 6, 'title' => 'Projections, transformations, and accurate measurement', 'desc' => 'Projection distortion, assigning versus transforming a CRS, combining different CRSs, and choosing suitable distance/area calculations.', 'status' => 'ready', 'dir' => 'Chapter_06', 'modules' => [
        ['id' => '6.1', 'file' => 'm1-distortion', 'title' => 'Why flattening costs something'],
        ['id' => '6.2', 'file' => 'm2-assign-transform', 'title' => 'Label vs transform'],
        ['id' => '6.3', 'file' => 'm3-datum', 'title' => 'Datums and evidence'],
        ['id' => '6.4', 'file' => 'm4-display', 'title' => 'Lined up ≠ ready'],
        ['id' => '6.5', 'file' => 'm5-measure', 'title' => 'Planar vs geodesic'],
        ['id' => '6.6', 'file' => 'm6-choose', 'title' => 'Choose the method'],
        ['id' => '6.7', 'file' => 'm7-experiment', 'title' => 'The comparison'],
        ['id' => '6.8', 'file' => 'm8-lab', 'title' => 'Lab: two layers'],
        ['id' => '6.9', 'file' => 'm9-check', 'title' => 'Independent check'],
        ['id' => '6.10', 'file' => 'm10-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 7, 'title' => 'GIS data formats, sources, and metadata', 'desc' => 'GeoJSON, GeoPackage, Shapefile, GeoTIFF, CSV, and geodatabases. Checking source quality, currency, accuracy, and usage rights.', 'status' => 'ready', 'dir' => 'Chapter_07', 'modules' => [
        ['id' => '7.1', 'file' => 'm1-layers', 'title' => 'Model, file, container, service'],
        ['id' => '7.2', 'file' => 'm2-simple', 'title' => 'CSV and GeoJSON'],
        ['id' => '7.3', 'file' => 'm3-shapefile', 'title' => 'Shapefile'],
        ['id' => '7.4', 'file' => 'm4-containers', 'title' => 'GeoPackage and GeoTIFF'],
        ['id' => '7.5', 'file' => 'm5-geodatabase', 'title' => 'Geodatabases'],
        ['id' => '7.6', 'file' => 'm6-sources', 'title' => 'Sources and metadata'],
        ['id' => '7.7', 'file' => 'm7-checks', 'title' => 'Conversion checks'],
        ['id' => '7.8', 'file' => 'm8-lab', 'title' => 'Lab: convert and check'],
        ['id' => '7.9', 'file' => 'm9-check', 'title' => 'Independent check'],
        ['id' => '7.10', 'file' => 'm10-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 8, 'title' => 'GIS data modeling and relationships', 'desc' => 'Fields, IDs, domains, nulls, relationships, attachments, and time fields. Designing data for reliable collection, querying, and editing.', 'status' => 'ready', 'dir' => 'Chapter_08', 'modules' => [
        ['id' => '8.1', 'file' => 'm1-entities', 'title' => 'Things, events, questions'],
        ['id' => '8.2', 'file' => 'm2-geometry', 'title' => 'Shape and location rules'],
        ['id' => '8.3', 'file' => 'm3-fields', 'title' => 'Fields, blanks, dates'],
        ['id' => '8.4', 'file' => 'm4-ids', 'title' => 'Identifiers'],
        ['id' => '8.5', 'file' => 'm5-relationships', 'title' => 'Relationships'],
        ['id' => '8.6', 'file' => 'm6-rules', 'title' => 'Allowed values and rules'],
        ['id' => '8.7', 'file' => 'm7-history', 'title' => 'History, photos, changes'],
        ['id' => '8.8', 'file' => 'm8-lab', 'title' => 'Lab: fix a bad table'],
        ['id' => '8.9', 'file' => 'm9-check', 'title' => 'Independent check'],
        ['id' => '8.10', 'file' => 'm10-media', 'title' => 'Recap & next'],
      ]],
      ['n' => 9, 'title' => 'Data capture, editing, and quality', 'desc' => 'Digitizing, snapping, GPS/GNSS, geocoding, georeferencing, geometry validity, and topology rules.', 'status' => 'drafted'],
      ['n' => 10, 'title' => 'Attribute queries and spatial relationships', 'desc' => 'Filters, joins, intersects, contains, within, touches, and nearest. Boundary cases and the difference between table joins and spatial joins.', 'status' => 'drafted'],
      ['n' => 11, 'title' => 'Spatial analysis fundamentals', 'desc' => 'Buffer, clip, intersect, dissolve, spatial join, and aggregation. Selecting an operation, checking assumptions, and validating results.', 'status' => 'drafted'],
      ['n' => 12, 'title' => 'Cartography and interpreting maps correctly', 'desc' => 'Symbology, labels, classification, scale, visibility, legends, and accessibility. Distinguishing precision, accuracy, and resolution.', 'status' => 'ready', 'dir' => 'Chapter_12', 'modules' => [
        ['id' => '12.1', 'file' => 'm1-purpose', 'title' => 'Who is the map for?'],
        ['id' => '12.2', 'file' => 'm2-scale', 'title' => 'Scale is not accuracy'],
        ['id' => '12.3', 'file' => 'm3-symbols', 'title' => 'Match symbols to data'],
        ['id' => '12.4', 'file' => 'm4-classes', 'title' => 'Classification is a choice'],
        ['id' => '12.5', 'file' => 'm5-rates', 'title' => 'Totals, rates, density'],
        ['id' => '12.6', 'file' => 'm6-context', 'title' => 'Context; zero ≠ missing'],
        ['id' => '12.7', 'file' => 'm7-protection', 'title' => 'Presentation ≠ protection'],
        ['id' => '12.8', 'file' => 'm8-lab', 'title' => 'Lab: redesign a bad map'],
        ['id' => '12.9', 'file' => 'm9-check', 'title' => 'Check & Phase 1 exit'],
        ['id' => '12.10', 'file' => 'm10-media', 'title' => 'Recap & next'],
      ]],
    ],
  ],
  [
    'id' => 'phase-2', 'n' => 'Phase 2', 'title' => 'Prepare and publish GIS content with ArcGIS Pro',
    'checkpoint' => 'Prepare a clean dataset, produce a defensible map, publish a layer, and explain the relationship between the source data, service, portal item, and map.',
    'chapters' => [
      ['n' => 13, 'title' => 'ArcGIS Pro working fundamentals', 'desc' => 'Projects, maps, catalogs, connections, selections, tables, editing, and geoprocessing. Establishing an organized project workflow.', 'status' => 'planned'],
      ['n' => 14, 'title' => 'Geodatabase design and editing workflows', 'desc' => 'Create feature classes, domains, relationships, and attachments. Apply the data-modeling concepts learned earlier.', 'status' => 'planned'],
      ['n' => 15, 'title' => 'Data preparation and repeatable analysis', 'desc' => 'Import, clean, transform, join, and analyze data. Understand processing environments and introduce ModelBuilder for repeatable workflows.', 'status' => 'planned'],
      ['n' => 16, 'title' => 'Web GIS architecture and publishing concepts', 'desc' => 'Client, portal, server, and storage roles; items, service URLs, feature services, map/image services, and tiles. Prepare and publish suitable web layers.', 'status' => 'planned'],
      ['n' => 17, 'title' => '3D GIS and web scenes', 'desc' => 'Elevation, Z values, height references, terrain, extrusion, scenes, and scene layers. Understand when 3D adds useful information.', 'status' => 'planned'],
    ],
  ],
  [
    'id' => 'phase-3', 'n' => 'Phase 3', 'title' => 'Configure and operate ArcGIS Online',
    'intro' => 'ArcGIS Online includes mapping, hosted data, applications, sharing, and organization administration; these are taught as connected workflows.',
    'checkpoint' => 'Deliver a configured solution with separate editor and viewer access, a collection workflow, a dashboard, and an operating guide.',
    'chapters' => [
      ['n' => 18, 'title' => 'ArcGIS Online organization and access fundamentals', 'desc' => 'Members, user types, roles, groups, ownership, sharing, and licensing concepts. Establish appropriate access before publishing applications.', 'status' => 'planned'],
      ['n' => 19, 'title' => 'Hosted layers and data management', 'desc' => 'Hosted feature layers, views, editing permissions, attachments, editor tracking, updating data, and schema-change implications.', 'status' => 'planned'],
      ['n' => 20, 'title' => 'Web maps and Map Viewer configuration', 'desc' => 'Styles, labels, filters, pop-ups, forms, visibility, and map configuration. Introduce Arcade expressions in appropriate contexts.', 'status' => 'planned'],
      ['n' => 21, 'title' => 'Configurable applications and dashboards', 'desc' => 'Build applications with Instant Apps, Dashboards, and Experience Builder. Decide when configuration satisfies the requirement and when development is justified.', 'status' => 'planned'],
      ['n' => 22, 'title' => 'Field data collection and offline workflows', 'desc' => 'Survey123 and Field Maps concepts, form design, validation, offline areas, synchronization, and field-to-office workflows.', 'status' => 'planned'],
      ['n' => 23, 'title' => 'ArcGIS Online administration and governance', 'desc' => 'Organization settings, credit monitoring, content inventory, ownership transfer, sharing audits, dependencies, and content lifecycle procedures.', 'status' => 'planned'],
    ],
  ],
  [
    'id' => 'phase-4', 'n' => 'Phase 4', 'title' => 'Build custom ArcGIS applications and automation',
    'intro' => 'The team already knows software development, so these chapters concentrate on the GIS-specific concepts and failure modes.',
    'checkpoint' => 'Build an authenticated application that reads and edits GIS data, integrates with a backend, and handles failures correctly.',
    'chapters' => [
      ['n' => 24, 'title' => 'ArcGIS REST APIs and authentication', 'desc' => 'Portal and service endpoints, queries, pagination, spatial filters, edit operations, OAuth, API keys where supported, and authorization.', 'status' => 'planned'],
      ['n' => 25, 'title' => 'Custom web applications with ArcGIS Maps SDK for JavaScript', 'desc' => 'Maps/views, layers, renderers, events, selection, pop-ups, editing, and integration with the team’s frontend stack.', 'status' => 'planned'],
      ['n' => 26, 'title' => 'Extending configured applications', 'desc' => 'Experience Builder custom widgets and application integration. Evaluate extension versus a standalone custom application.', 'status' => 'planned'],
      ['n' => 27, 'title' => 'Python automation: ArcGIS API for Python and ArcPy', 'desc' => 'Distinguish portal/service automation from desktop geoprocessing. Automate data preparation, publishing, inventory, and reporting.', 'status' => 'planned'],
      ['n' => 28, 'title' => 'Backend integration and spatial databases', 'desc' => 'Connect business systems to GIS services; introduce PostGIS, spatial indexes, data synchronization, stable IDs, and reliable update handling.', 'status' => 'planned'],
      ['n' => 29, 'title' => 'Application quality, performance, and delivery', 'desc' => 'Test spatial correctness and permissions; handle large datasets, failed requests, edit conflicts, environment configuration, logging, and deployment.', 'status' => 'planned'],
    ],
  ],
  [
    'id' => 'phase-5', 'n' => 'Phase 5', 'title' => 'Deploy, administer, and operate ArcGIS Enterprise',
    'intro' => 'A separate engineering competency. Being able to build an ArcGIS application does not establish readiness to administer a production Enterprise deployment.',
    'checkpoint' => 'Deploy a training environment, publish a secured service, diagnose an introduced failure, and demonstrate recovery from backup. Installation alone is not a pass.',
    'chapters' => [
      ['n' => 30, 'title' => 'ArcGIS Enterprise architecture', 'desc' => 'Portal, ArcGIS Server, hosting server, ArcGIS Data Store, web access components, and federation. Trace requests and distinguish Enterprise from Online.', 'status' => 'planned'],
      ['n' => 31, 'title' => 'Infrastructure and deployment planning', 'desc' => 'Supported deployment options, capacity, operating systems, DNS, TLS certificates, networking, storage, service accounts, licensing, and compatibility.', 'status' => 'planned'],
      ['n' => 32, 'title' => 'Deploying a training environment', 'desc' => 'Install and configure a supported base deployment; configure web access, federation, and hosting; validate component health and connectivity.', 'status' => 'planned'],
      ['n' => 33, 'title' => 'Enterprise publishing and data architecture', 'desc' => 'Hosted versus referenced data, registered data sources, enterprise geodatabases, database permissions, service capabilities, and versioning concepts.', 'status' => 'planned'],
      ['n' => 34, 'title' => 'Enterprise identity, security, and administration', 'desc' => 'Identity-provider integration, roles, groups, service access, credential management, administrative boundaries, and auditing.', 'status' => 'planned'],
      ['n' => 35, 'title' => 'Monitoring, troubleshooting, and performance', 'desc' => 'Logs, service health, resource usage, failed publishing, slow queries, storage growth, and incident diagnosis.', 'status' => 'planned'],
      ['n' => 36, 'title' => 'Backup, recovery, upgrades, and availability', 'desc' => 'Supported backup procedures, restore drills, recovery objectives, upgrade planning, dependencies, rollback planning, and high-availability concepts.', 'status' => 'planned'],
    ],
  ],
  [
    'id' => 'phase-6', 'n' => 'Capstone', 'title' => 'Integrated delivery and handover project',
    'chapters' => [
      ['n' => 37, 'title' => 'Integrated delivery and handover project', 'desc' => 'Combine the phases into one realistic solution: data preparation, configured application, custom functionality, access control, deployment, monitoring, and operational documentation.', 'status' => 'planned'],
    ],
  ],
];
